# Matrix Decomposition

A matrix decomposition is a way of reducing a matrix into its constituent parts. It is an approach that can simplify more complex matrix operations that can be performed on the decomposed matrix rather than on the original matrix itself.

## Dictionary Learning

Finds a dictionary (a set of atoms) that performs well at sparsely encoding the fitted data.

In [1]:
import numpy as np
from sklearn.datasets import make_sparse_coded_signal
from sklearn.decomposition import DictionaryLearning
X, dictionary, code = make_sparse_coded_signal(
    n_samples=100, n_components=15, n_features=20, n_nonzero_coefs=10,
    random_state=42, data_transposed=False
)
dict_learner = DictionaryLearning(
    n_components=15, transform_algorithm='lasso_lars', transform_alpha=0.1,
    random_state=42,
)
X_transformed = dict_learner.fit_transform(X)

### We can check the level of sparsity of X_transformed:

In [2]:
np.mean(X_transformed == 0)

0.41733333333333333

We can compare the average squared euclidean norm of the reconstruction error of the sparse coded signal relative to the squared euclidean norm of the original signal

In [3]:
X_hat = X_transformed @ dict_learner.components_
np.mean(np.sum((X_hat - X) ** 2, axis=1) / np.sum(X ** 2, axis=1))

0.07777084613290733

## Factor Analysis

FactorAnalysis performs a maximum likelihood estimate of the so-called loading matrix, the transformation of the latent variables to the observed ones, using SVD based approach.

In [4]:
from sklearn.datasets import load_digits
from sklearn.decomposition import FactorAnalysis
X, _ = load_digits(return_X_y=True)
transformer = FactorAnalysis(n_components=7, random_state=0)
X_transformed = transformer.fit_transform(X)
X_transformed.shape

(1797, 7)

## FastICA

A fast algorithm for Independent Component Analysis.

In [5]:
from sklearn.datasets import load_digits
from sklearn.decomposition import FastICA
X, _ = load_digits(return_X_y=True)
transformer = FastICA(n_components=7,
        random_state=0,
        whiten='unit-variance')
X_transformed = transformer.fit_transform(X)
X_transformed.shape

c:\Python310\lib\site-packages\sklearn\decomposition\_fastica.py:120: ConvergenceWarning: FastICA did not converge. Consider increasing tolerance or the maximum number of iterations.
  warnings.warn(


(1797, 7)

## Incremental PCA

Depending on the size of the input data, this algorithm can be much more memory efficient than a PCA, and allows sparse input.

In [6]:
from sklearn.datasets import load_digits
from sklearn.decomposition import IncrementalPCA
from scipy import sparse
X, _ = load_digits(return_X_y=True)
transformer = IncrementalPCA(n_components=7, batch_size=200)
# either partially fit on smaller batches of data
transformer.partial_fit(X[:100, :])

# or let the fit function itself divide the data into batches
X_sparse = sparse.csr_matrix(X)
X_transformed = transformer.fit_transform(X_sparse)
X_transformed.shape

(1797, 7)

In [8]:
import numpy as np
from sklearn.decomposition import IncrementalPCA
X = np.array([[-1, -1], [-2, -1], [-3, -2],
              [1, 1], [2, 1], [3, 2]])
ipca = IncrementalPCA(n_components=2, batch_size=3)
ipca.fit(X)
ipca.transform(X) 

array([[-1.38340578, -0.2935787 ],
       [-2.22189802,  0.25133484],
       [-3.6053038 , -0.04224385],
       [ 1.38340578,  0.2935787 ],
       [ 2.22189802, -0.25133484],
       [ 3.6053038 ,  0.04224385]])

## Kernel PCA

Non-linear dimensionality reduction through the use of kernels (see Pairwise metrics, Affinities and Kernels).

kernels ==> ‘linear’, ‘poly’, ‘rbf’, ‘sigmoid’, ‘cosine’, ‘precomputed’

In [1]:
from sklearn.datasets import load_digits
from sklearn.decomposition import KernelPCA
X, _ = load_digits(return_X_y=True)
transformer = KernelPCA(n_components=7, kernel='linear')
X_transformed = transformer.fit_transform(X)
X_transformed.shape

(1797, 7)

## Latent Dirichlet Allocation

Latent Dirichlet Allocation with online variational Bayes algorithm.

In [2]:
from sklearn.decomposition import LatentDirichletAllocation
from sklearn.datasets import make_multilabel_classification
# This produces a feature matrix of token counts, similar to what
# CountVectorizer would produce on text.
X, _ = make_multilabel_classification(random_state=0)
lda = LatentDirichletAllocation(n_components=5,
    random_state=0)
lda.fit(X)
# get topics for some given samples:
lda.transform(X[-2:])

array([[0.00360392, 0.25499205, 0.0036211 , 0.64236448, 0.09541846],
       [0.15297572, 0.00362644, 0.44412786, 0.39568399, 0.003586  ]])

## Mini Batch Dictionary Learning

Finds a dictionary (a set of atoms) that performs well at sparsely encoding the fitted data.

In [3]:
import numpy as np
from sklearn.datasets import make_sparse_coded_signal
from sklearn.decomposition import MiniBatchDictionaryLearning
X, dictionary, code = make_sparse_coded_signal(
    n_samples=100, n_components=15, n_features=20, n_nonzero_coefs=10,
    random_state=42, data_transposed=False)
dict_learner = MiniBatchDictionaryLearning(
    n_components=15, batch_size=3, transform_algorithm='lasso_lars',
    transform_alpha=0.1, random_state=42)
X_transformed = dict_learner.fit_transform(X)

In [4]:
np.mean(X_transformed == 0)

0.38466666666666666

In [5]:
X_hat = X_transformed @ dict_learner.components_
np.mean(np.sum((X_hat - X) ** 2, axis=1) / np.sum(X ** 2, axis=1))

0.0597265626470165

## Mini Batch Sparse PCA

Finds the set of sparse components that can optimally reconstruct the data. The amount of sparseness is controllable by the coefficient of the L1 penalty, given by the parameter alpha.

In [6]:
import numpy as np
from sklearn.datasets import make_friedman1
from sklearn.decomposition import MiniBatchSparsePCA
X, _ = make_friedman1(n_samples=200, n_features=30, random_state=0)
transformer = MiniBatchSparsePCA(n_components=5, batch_size=50, random_state=0)
transformer.fit(X)

X_transformed = transformer.transform(X)
X_transformed.shape

(200, 5)

In [7]:
# most values in the components_ are zero (sparsity)
np.mean(transformer.components_ == 0)

0.94

## NMF (Non-Negative Matrix Factorization)

Find two non-negative matrices, i.e. matrices with all non-negative elements, (W, H) whose product approximates the non-negative matrix X. This factorization can be used for example for dimensionality reduction, source separation or topic extraction.

In [9]:
import numpy as np
X = np.array([[1, 1], [2, 1], [3, 1.2], [4, 1], [5, 0.8], [6, 1]])
from sklearn.decomposition import NMF
model = NMF(n_components=2, init='random', random_state=0)
W = model.fit_transform(X)
H = model.components_
H

array([[2.09783018, 0.30560234],
       [2.13443044, 2.13171694]])

## Mini Batch NMF

In [10]:
import numpy as np
X = np.array([[1, 1], [2, 1], [3, 1.2], [4, 1], [5, 0.8], [6, 1]])
from sklearn.decomposition import MiniBatchNMF
model = MiniBatchNMF(n_components=2, init='random', random_state=0)
W = model.fit_transform(X)
H = model.components_
H

/home/devangm/.local/lib/python3.10/site-packages/sklearn/decomposition/_nmf.py:2308: ConvergenceWarning: Maximum number of iterations 200 reached. Increase it to improve convergence.
  warnings.warn(


array([[2.36064875, 0.13259228],
       [1.4397403 , 1.38388453]])

## PCA

Linear dimensionality reduction using Singular Value Decomposition of the data to project it to a lower dimensional space. The input data is centered but not scaled for each feature before applying the SVD.

In [12]:
import numpy as np
from sklearn.decomposition import PCA
X = np.array([[-1, -1], [-2, -1], [-3, -2], [1, 1], [2, 1], [3, 2]])
pca = PCA(n_components=2)
pca.fit(X)
print(pca.explained_variance_ratio_)
print(pca.singular_values_)

[0.99244289 0.00755711]
[6.30061232 0.54980396]


In [13]:
pca = PCA(n_components=2, svd_solver='full')
pca.fit(X)
PCA(n_components=2, svd_solver='full')
print(pca.explained_variance_ratio_)
print(pca.singular_values_)

[0.99244289 0.00755711]
[6.30061232 0.54980396]


In [14]:
pca = PCA(n_components=1, svd_solver='arpack')
pca.fit(X)
PCA(n_components=1, svd_solver='arpack')
print(pca.explained_variance_ratio_)
print(pca.singular_values_)

[0.99244289]
[6.30061232]


## Sparse PCA

Finds the set of sparse components that can optimally reconstruct the data. The amount of sparseness is controllable by the coefficient of the L1 penalty, given by the parameter alpha.

In [16]:
import numpy as np
from sklearn.datasets import make_friedman1
from sklearn.decomposition import SparsePCA
X, _ = make_friedman1(n_samples=200, n_features=30, random_state=0)
transformer = SparsePCA(n_components=5, random_state=0)
transformer.fit(X)
X_transformed = transformer.transform(X)
X_transformed.shape

(200, 5)

In [17]:
# most values in the components_ are zero (sparsity)
np.mean(transformer.components_ == 0)

0.9666666666666667

## Sparse Coder

Finds a sparse representation of data against a fixed, precomputed dictionary.

Each row of the result is the solution to a sparse coding problem. The goal is to find a sparse array code such that:

In [18]:
import numpy as np
from sklearn.decomposition import SparseCoder
X = np.array([[-1, -1, -1], [0, 0, 3]])
dictionary = np.array(
    [[0, 1, 0],
    [-1, -1, 2],
    [1, 1, 1],
    [0, 1, 1],
    [0, 2, 1]],
  dtype=np.float64
)
coder = SparseCoder(
    dictionary=dictionary, transform_algorithm='lasso_lars',
    transform_alpha=1e-10,
)
coder.transform(X)

array([[ 0.,  0., -1.,  0.,  0.],
       [ 0.,  1.,  1.,  0.,  0.]])

## Truncated SVD

Dimensionality reduction using truncated SVD (aka LSA).

This transformer performs linear dimensionality reduction by means of truncated singular value decomposition (SVD). Contrary to PCA, this estimator does not center the data before computing the singular value decomposition. This means it can work with sparse matrices efficiently.

In [19]:
from sklearn.decomposition import TruncatedSVD
from scipy.sparse import csr_matrix
import numpy as np
np.random.seed(0)
X_dense = np.random.rand(100, 100)
X_dense[:, 2 * np.arange(50)] = 0
X = csr_matrix(X_dense)
svd = TruncatedSVD(n_components=5, n_iter=7, random_state=42)
svd.fit(X)
print(svd.explained_variance_ratio_)
print(svd.explained_variance_ratio_.sum())
print(svd.singular_values_)

[0.01570766 0.05122679 0.04998062 0.04795064 0.04539933]
0.2102650346507035
[35.24105443  4.5981613   4.54200434  4.44866153  4.32887456]
