# Cross Decomposition

The cross decomposition module contains supervised estimators for dimensionality reduction and regression, belonging to the “Partial Least Squares” family. Cross decomposition algorithms find the fundamental relations between two matrices (X and Y).

## CCA

Canonical Correlation Analysis, also known as “Mode B” PLS.

In [2]:
from sklearn.cross_decomposition import CCA
X = [[0., 0., 1.], [1.,0.,0.], [2.,2.,2.], [3.,5.,4.]]
Y = [[0.1, -0.2], [0.9, 1.1], [6.2, 5.9], [11.9, 12.3]]
cca = CCA(n_components=1)
cca.fit(X, Y)
X_c, Y_c = cca.transform(X, Y)
X_c

array([[-1.3373174 ],
       [-1.10847164],
       [ 0.40763151],
       [ 2.03815753]])

## PLS Canonical

Partial Least Squares transformer and regressor.

In [4]:
from sklearn.cross_decomposition import PLSCanonical
X = [[0., 0., 1.], [1.,0.,0.], [2.,2.,2.], [2.,5.,4.]]
Y = [[0.1, -0.2], [0.9, 1.1], [6.2, 5.9], [11.9, 12.3]]
plsca = PLSCanonical(n_components=2)
plsca.fit(X, Y)
X_c, Y_c = plsca.transform(X, Y)
Y_c

array([[-1.22601804, -0.01674181],
       [-0.9602955 ,  0.04216316],
       [ 0.32491535, -0.04379   ],
       [ 1.86139819,  0.01836865]])

## PLS Regression

PLSRegression is also known as PLS2 or PLS1, depending on the number of targets.

In [6]:
from sklearn.cross_decomposition import PLSRegression
X = [[0., 0., 1.], [1.,0.,0.], [2.,2.,2.], [2.,5.,4.]]
Y = [[0.1, -0.2], [0.9, 1.1], [6.2, 5.9], [11.9, 12.3]]
pls2 = PLSRegression(n_components=2)
pls2.fit(X, Y)
Y_pred = pls2.predict(X)
Y_pred

array([[ 0.26087869,  0.15302213],
       [ 0.60667302,  0.45634164],
       [ 6.46856199,  6.48931562],
       [11.7638863 , 12.00132061]])

## PLS SVD

This transformer simply performs a SVD on the cross-covariance matrix X'Y. It is able to project both the training data X and the targets Y. The training data X is projected on the left singular vectors, while the targets are projected on the right singular vectors.

In [7]:
import numpy as np
from sklearn.cross_decomposition import PLSSVD
X = np.array([[0., 0., 1.],
              [1., 0., 0.],
              [2., 2., 2.],
              [2., 5., 4.]])
Y = np.array([[0.1, -0.2],
              [0.9, 1.1],
              [6.2, 5.9],
              [11.9, 12.3]])
pls = PLSSVD(n_components=2).fit(X, Y)
X_c, Y_c = pls.transform(X, Y)
X_c.shape, Y_c.shape

((4, 2), (4, 2))