Feature Scaling is done with speedup gradient descent convergence, or to reduce average euclidian distance and overall ML model performance in many models

We should not use feature scaling in Decision Tree, random forest, XGBoost

In [1]:
import pandas as pd
import numpy as np

In [2]:
dataset = pd.read_csv("data.csv", delimiter=';')
df = dataset.head(11)
df

Car     MPG Cylinders Displacement Horsepower  \
0                      STRING  DOUBLE       INT       DOUBLE     DOUBLE   
1   Chevrolet Chevelle Malibu    18.0         8        307.0      130.0   
2           Buick Skylark 320    15.0         8        350.0      165.0   
3          Plymouth Satellite    18.0         8        318.0      150.0   
4               AMC Rebel SST    16.0         8        304.0      150.0   
5                 Ford Torino    17.0         8        302.0      140.0   
6            Ford Galaxie 500    15.0         8        429.0      198.0   
7            Chevrolet Impala    14.0         8        454.0      220.0   
8           Plymouth Fury iii    14.0         8        440.0      215.0   
9            Pontiac Catalina    14.0         8        455.0      225.0   
10         AMC Ambassador DPL    15.0         8        390.0      190.0   

    Weight Acceleration Model Origin  
0   DOUBLE       DOUBLE   INT    CAT  
1    3504.         12.0    70     US  
2    3693.         11.5    70     US  
3    3436.         11.0    70     US  
4    3433.         12.0    70     US  
5    3449.         10.5    70     US  
6    4341.         10.0    70     US  
7    4354.          9.0    70     US  
8    4312.          8.5    70     US  
9    4425.         10.0    70     US  
10   3850.          8.5    70     US

In [3]:
buy = ['FLOAT', 0, 0, 0, 0, 0, 1, 1, 1, 1, 0]
df['Buy']=buy
df

/tmp/ipykernel_32991/4184335015.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Buy']=buy


Car     MPG Cylinders Displacement Horsepower  \
0                      STRING  DOUBLE       INT       DOUBLE     DOUBLE   
1   Chevrolet Chevelle Malibu    18.0         8        307.0      130.0   
2           Buick Skylark 320    15.0         8        350.0      165.0   
3          Plymouth Satellite    18.0         8        318.0      150.0   
4               AMC Rebel SST    16.0         8        304.0      150.0   
5                 Ford Torino    17.0         8        302.0      140.0   
6            Ford Galaxie 500    15.0         8        429.0      198.0   
7            Chevrolet Impala    14.0         8        454.0      220.0   
8           Plymouth Fury iii    14.0         8        440.0      215.0   
9            Pontiac Catalina    14.0         8        455.0      225.0   
10         AMC Ambassador DPL    15.0         8        390.0      190.0   

    Weight Acceleration Model Origin    Buy  
0   DOUBLE       DOUBLE   INT    CAT  FLOAT  
1    3504.         12.0    70     US      0  
2    3693.         11.5    70     US      0  
3    3436.         11.0    70     US      0  
4    3433.         12.0    70     US      0  
5    3449.         10.5    70     US      0  
6    4341.         10.0    70     US      1  
7    4354.          9.0    70     US      1  
8    4312.          8.5    70     US      1  
9    4425.         10.0    70     US      1  
10   3850.          8.5    70     US      0

In [4]:
independent=df.iloc[1:,1:7].values
independent

array([['18.0', '8', '307.0', '130.0', '3504.', '12.0'],
       ['15.0', '8', '350.0', '165.0', '3693.', '11.5'],
       ['18.0', '8', '318.0', '150.0', '3436.', '11.0'],
       ['16.0', '8', '304.0', '150.0', '3433.', '12.0'],
       ['17.0', '8', '302.0', '140.0', '3449.', '10.5'],
       ['15.0', '8', '429.0', '198.0', '4341.', '10.0'],
       ['14.0', '8', '454.0', '220.0', '4354.', '9.0'],
       ['14.0', '8', '440.0', '215.0', '4312.', '8.5'],
       ['14.0', '8', '455.0', '225.0', '4425.', '10.0'],
       ['15.0', '8', '390.0', '190.0', '3850.', '8.5']], dtype=object)

In [5]:
dependent = df.iloc[1:, 9:].values
dependent

array([[0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0]], dtype=object)

In [6]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(independent,dependent,test_size=0.2,random_state=0)

### Standard Scaler

In [7]:
from sklearn.preprocessing import StandardScaler
stndrd = StandardScaler()
x_train = stndrd.fit_transform(x_train)
x_train

array([[ 1.13389342,  0.        , -1.15956196, -1.11457245, -1.08595059,
         0.1796053 ],
       [-0.37796447,  0.        ,  0.29817307,  0.43344484, -0.04416545,
        -1.25723711],
       [-0.37796447,  0.        , -0.36443376, -0.3405638 , -0.45204642,
         0.89802651],
       [-1.13389342,  0.        ,  1.35834401,  1.36225522,  1.26521037,
        -0.89802651],
       [-1.13389342,  0.        ,  1.12643162,  1.20745349,  1.15609572,
        -1.25723711],
       [ 0.37796447,  0.        , -1.12643162, -0.80496899, -1.12751807,
         1.25723711],
       [ 1.88982237,  0.        , -1.0767361 , -1.42417591, -0.94306235,
         1.25723711],
       [-0.37796447,  0.        ,  0.94421474,  0.68112761,  1.23143679,
        -0.1796053 ]])

In [8]:
x_test = stndrd.transform(x_test)
x_test

array([[ 1.88982237,  0.        , -0.89451922, -0.80496899, -1.11972417,
         0.53881591],
       [-1.13389342,  0.        ,  1.37490918,  1.51705695,  1.44966609,
        -0.1796053 ]])

### MaxAbsScaler

Scale each feature by its maximum absolute value

In [9]:
from sklearn.preprocessing import MaxAbsScaler
mxabs = MaxAbsScaler()
x_train = mxabs.fit_transform(x_train)
x_train

array([[ 0.6       ,  0.        , -0.85365854, -0.7826087 , -0.85831622,
         0.14285714],
       [-0.2       ,  0.        ,  0.2195122 ,  0.30434783, -0.0349076 ,
        -1.        ],
       [-0.2       ,  0.        , -0.26829268, -0.23913043, -0.35728953,
         0.71428571],
       [-0.6       ,  0.        ,  1.        ,  0.95652174,  1.        ,
        -0.71428571],
       [-0.6       ,  0.        ,  0.82926829,  0.84782609,  0.9137577 ,
        -1.        ],
       [ 0.2       ,  0.        , -0.82926829, -0.56521739, -0.89117043,
         1.        ],
       [ 1.        ,  0.        , -0.79268293, -1.        , -0.74537988,
         1.        ],
       [-0.2       ,  0.        ,  0.69512195,  0.47826087,  0.97330595,
        -0.14285714]])

In [10]:
x_test = mxabs.transform(x_test)
x_test

array([[ 1.        ,  0.        , -0.65853659, -0.56521739, -0.88501027,
         0.42857143],
       [-0.6       ,  0.        ,  1.01219512,  1.06521739,  1.14579055,
        -0.14285714]])

### MinMaxScaler

Transform features by scaling each feature to a given range

In [11]:
from sklearn.preprocessing import MinMaxScaler
minmax = MinMaxScaler()
x_train = minmax.fit_transform(x_train)
x_train

array([[0.75      , 0.        , 0.        , 0.11111111, 0.01737242,
        0.57142857],
       [0.25      , 0.        , 0.57894737, 0.66666667, 0.45276873,
        0.        ],
       [0.25      , 0.        , 0.31578947, 0.38888889, 0.28230185,
        0.85714286],
       [0.        , 0.        , 1.        , 1.        , 1.        ,
        0.14285714],
       [0.        , 0.        , 0.90789474, 0.94444444, 0.95439739,
        0.        ],
       [0.5       , 0.        , 0.01315789, 0.22222222, 0.        ,
        1.        ],
       [1.        , 0.        , 0.03289474, 0.        , 0.07709012,
        1.        ],
       [0.25      , 0.        , 0.83552632, 0.75555556, 0.98588491,
        0.42857143]])

In [12]:
x_test = minmax.transform(x_test)
x_test

array([[1.        , 0.        , 0.10526316, 0.22222222, 0.00325733,
        0.71428571],
       [0.        , 0.        , 1.00657895, 1.05555556, 1.07709012,
        0.42857143]])

### Robust Scaler

Scale features using statistics that are robust to outliers

In [13]:
from sklearn.preprocessing import RobustScaler
rbst = RobustScaler()
x_train = rbst.fit_transform(x_train)
x_train

array([[ 1.33333333,  0.        , -0.54183267, -0.68493151, -0.38902292,
         0.09090909],
       [ 0.        ,  0.        ,  0.15936255,  0.2283105 ,  0.0946924 ,
        -0.63636364],
       [ 0.        ,  0.        , -0.15936255, -0.2283105 , -0.0946924 ,
         0.45454545],
       [-0.66666667,  0.        ,  0.66932271,  0.77625571,  0.7026538 ,
        -0.45454545],
       [-0.66666667,  0.        ,  0.55776892,  0.68493151,  0.65199035,
        -0.63636364],
       [ 0.66666667,  0.        , -0.52589641, -0.50228311, -0.40832328,
         0.63636364],
       [ 2.        ,  0.        , -0.50199203, -0.86757991, -0.32267793,
         0.63636364],
       [ 0.        ,  0.        ,  0.47011952,  0.37442922,  0.68697226,
        -0.09090909]])

In [14]:
x_test = rbst.transform(x_test)
x_test

array([[ 2.        ,  0.        , -0.41434263, -0.50228311, -0.40470446,
         0.27272727],
       [-0.66666667,  0.        ,  0.67729084,  0.86757991,  0.78829916,
        -0.09090909]])